# Generated by Django 4.1 on 2024-07-05 10:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('department_number', models.IntegerField(null=True)),
                ('department_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monthly_projects', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_monthly_users', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_monthly_files', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_projects', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_users', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_files', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('files', models.FileField(null=True, upload_to='userprofiles/')),
                ('date', models.DateField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.deparment')),
                ('userprofile', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('files', models.FileField(null=True, upload_to='document/')),
                ('date', models.DateField(null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
                ('userprofile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='deparment',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Deparments', to='core.userprofile'),
        ),
    ]
