# Generated by Django 4.1 on 2024-07-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='home_address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
