# Generated by Django 4.1 on 2024-07-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_date_created_userprofile_date_modified'),
        ('core', '0004_rename_home_address_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparment',
            name='user_userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='document',
            name='user_userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.userprofile'),
        ),
    ]
