# Generated by Django 4.1 on 2024-07-09 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_projectsite_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='file_type',
            field=models.CharField(blank=True, choices=[('shapfile', 'ShapeFile')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
