# Generated by Django 4.1 on 2024-07-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectsite_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsite',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='projectsite',
            name='files',
        ),
    ]
