# Generated by Django 4.1 on 2024-07-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projectsite_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='total_annual_files',
            new_name='annual_total_projects',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='total_annual_users',
            new_name='annual_total_users',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='total_annual_projects',
            new_name='monthly_total_projects',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='total_monthly_files',
            new_name='monthly_total_users',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_projects',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_users',
        ),
    ]
