# Generated by Django 4.1 on 2024-07-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_total_annual_files_summary_annual_total_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsite',
            name='files',
        ),
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='shapefile/')),
                ('uploaded_date', models.DateField(null=True)),
                ('projectsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projectsite')),
            ],
        ),
    ]
