# Generated by Django 4.1 on 2024-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='files',
            field=models.FileField(null=True, upload_to='userprofiles/'),
        ),
    ]
