# Generated by Django 4.1 on 2024-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
